### PR TITLE
ciao-controller: Fix workload's image ID reference in ciao-cli output

### LINKED ISSUE #1232: ciao-controller: Image ID is not shown when workloads listing
ImageID is not shown when running:

```
ciao-cli workload list
```

Steps to reproduce it
----------------------
- Create a workload with this https://github.com/01org/ciao/blob/master/ciao-cli/examples/fedora_cloud.yaml
- Run ``ciao-cli workload list``

You will see this output:
```
Workload 1
        Name: Fedora VM no storage
        UUID:3f875e60-da16-46c9-8a9a-dfc60d790611
        Image UUID: 
        CPUs: 2
        Memory: 128 MB
```

### PR DESCRIPTION
**Pull request by obedmr**
This commit fixes OpenStack's compatibility for Disk variable, it's not the Image ID, it refers to the primary disk's size according to OpenStack [Flavor Details API method](https://developer.openstack.org/api-ref/compute/?expanded=list-flavors-with-details-detail#list-flavors-with-details).

A new CIAO specific API will be required in order to show image and storage details. This should be addressed in a separate PR.

Addresses part of #1232

Signed-off-by: Obed N Munoz <obed.n.munoz@intel.com>

### CODE REVIEW

File: ciao-controller/openstack_compute.go [hunk 1]
```diff
@@ -569,6 +569,10 @@ func buildFlavorDetails(workload types.Workload) (compute.FlavorDetails, error)
 	details.Disk = workload.ImageID
 	details.Name = workload.Description
 
+	if details.Disk == "" {
+		details.Disk = workload.Storage[0].SourceID
```
Comment (rbradford) [inline ciao-controller/openstack_compute.go]: This would be wrong if the workload used a volume rather than an image.

Comment (rbradford) [inline ciao-controller/openstack_compute.go]: It will also still be wrong for containers too.

Comment (obedmr) [inline ciao-controller/openstack_compute.go]: @rbradford ok got it, so, is this ok to have empty value in ``ciao-cli`` output when we use ciao-image provided image?

**Comment by obedmr** [comment]
@rbradford a got it, showing disks information will be more useful and clear.

**Comment by obedmr** [comment]
/me making proper changes to be in complience with openstack API https://developer.openstack.org/api-ref/compute/?expanded=list-flavors-with-details-detail#list-flavors-with-details

**Comment by obedmr** [comment]
@rbradford I changed the change to remove the Image ID from current implementation.
