### PR TITLE
Unittests: more commonizing

### LINKED ISSUE #103: scheduler test coverage
I have the worst test coverage on the project and need to redeem myself.  The ancient test bits I'd written in fake_agent.go and fake_controller.go need morphed into a go test cases which exercise the successful and failed flow of workloads through the scheduling algorithm.

### LINKED ISSUE #137: make test functionality global
Many of us are duplicating effort writing fake schedulers, fake launchers, fake controllers to do unit testing.  In addition as we add more external component dependencies (like keystone) we have to fake those too.  We should create a "ciao-test" package that can provide this functionality so that we can all use it.

### PR DESCRIPTION
**Pull request by tpepper**
This PR represents changes to testutil/ which enable a common test agent, test controller, test server, test yaml sample files and an integrated client/server test spanning ssntp flows between controller, server, agent and netagent.

The races referred to broadly in issue #83 (which was opened without and test -race traces) are addressed here, but there are more that still need fixed.

Fixes #137 

Fixes #103

### CODE REVIEW

**Comment by tpepper** [comment]
Don't merge yet.  I'll add some testutil/*_test.go so coverage doesn't appear to have gone down.  Everything in testutil/ here has coverage as it's used solely but other _test.go files, but...the tools can't see that.  They see a new package with basically no coverage of it's exported code.

File: ciao-controller/controller_test.go [hunk 1]
```diff
@@ -742,7 +723,12 @@ func testStartTracedWorkload(t *testing.T) *testutil.SsntpTestClient {
 		t.Fatal(err)
 	}
 
-	client := newTestClient(0, ssntp.AGENT)
+	client, err := testutil.NewSsntpTestClientConnection("StartTracedWorkload", ssntp.AGENT)
+	if err != nil {
+		t.Fatal(err)
+	}
+	// deliberately leak
+	//defer client.Ssntp.Close()
```
Comment (kaccardi) [inline ciao-controller/controller_test.go]: why is this here?

File: ssntp/client.go [hunk 2]
```diff
@@ -368,7 +368,7 @@ func (client *Client) sendCommand(cmd Command, payload []byte, trace *TraceConfi
 	client.status.Lock()
 	if client.status.status == ssntpClosed {
 		client.status.Unlock()
-		return -1, fmt.Errorf("Client not connected")
+		return -1, fmt.Errorf("sendCommand: Client not connected")
 	}
 	client.status.Unlock()
```
Comment (kaccardi) [inline ssntp/client.go]: I wonder if we need to add the clients name as well, in case of multiple clients.

File: ciao-controller/controller_test.go (hunk 1 above)
Comment (tpepper) [inline ciao-controller/controller_test.go]: It looks to me like you're deliberately not closing the connection.  But I'm inferring the design of the overall test.  You tell me :)

File: ssntp/client.go (hunk 2 above)
Comment (tpepper) [inline ssntp/client.go]: Name and uuid, if we're actually thinking somebody will track it back to the running thing that got missed.  My inclination is to think nobody's going to see that or care.  Maybe the message should be more like "sendCommand: discarding command to disconnected client"?

**Comment by sameo** [comment]
All SSNTP changes look good to me, thanks.

File: ciao-controller/controller_test.go (hunk 1 above)
Comment (kaccardi) [inline ciao-controller/controller_test.go]: ah ok, I reviewed the code, I did want to have the caller close the connection when they were done with it.

File: ciao-controller/controller_test.go [hunk 3]
```diff
@@ -784,7 +770,12 @@ func testStartWorkload(t *testing.T, num int, fail bool, reason payloads.StartFa
 		t.Fatal(err)
 	}
 
-	client := newTestClient(0, ssntp.AGENT)
+	client, err := testutil.NewSsntpTestClientConnection("StartWorkload", ssntp.AGENT)
+	if err != nil {
+		t.Fatal(err)
+	}
+	// deliberately leak
+	//defer client.Ssntp.Close()
```
Comment (kaccardi) [inline ciao-controller/controller_test.go]: Same comment as above, replace the comment "deliberately leak", with "Caller is responsible for closing connection".

File: ciao-controller/controller_test.go [hunk 4]
```diff
@@ -823,7 +814,12 @@ func testStartWorkload(t *testing.T, num int, fail bool, reason payloads.StartFa
 }
 
 func testStartWorkloadLaunchCNCI(t *testing.T, num int) (*testutil.SsntpTestClient, []*types.Instance) {
-	netClient := newTestClient(0, ssntp.NETAGENT)
+	netClient, err := testutil.NewSsntpTestClientConnection("StartWorkloadLaunchCNCI", ssntp.NETAGENT)
+	if err != nil {
+		t.Fatal(err)
+	}
+	// deliberately leak
+	//defer netClient.Ssntp.Close()
```
Comment (kaccardi) [inline ciao-controller/controller_test.go]: same as above, replace comment with "Caller is responsible for closing connection"

File: ssntp/client.go (hunk 2 above)
Comment (kaccardi) [inline ssntp/client.go]: I guess we can always change it later if we decide we want that extra level of detail.  So, make it say whatever you want.

**Comment by markdryan** [comment]
@tpepper Just a quick comment.  You need to add testutil to the test-cases command that runs the unit tests in .travis.yml.  There are 3 test-cases commands.  The first runs tests in packages that do not need to be root, so I guess it makes sense to add them to this one, e.g.,

```
   - test-cases -text -coverprofile /tmp/cover.out -short github.com/01org/ciao/ciao-launcher github.com/01org/ciao/ciao-scheduler github.com/01org/ciao/ciao-controller/... github.com/01org/ciao/payloads
```

**Comment by sameo** [comment]
It all looks good to me, but this PR needs to be rebased on master.

**Comment by tpepper** [comment]
I'm still adding test coverage for the testutil/ library code.  Will rebase once that's a tad further.
