### PR TITLE
ciao-image: Add more logging information

### LINKED ISSUE #779: ciao-image has almost no logs
There are a few logs written if the service fails to start but apart from that there's nothing.  This makes it a little hard to debug problems.

### PR DESCRIPTION
**Pull request by obedmr**
In order to improve debugging, we need more logging in ciao-image service. Below the main events that are planned to be logged.

- Init information
- Errors reporting
- Basic information on image CRUD operations

It fixes #779

Signed-off-by: Obed N Munoz <obed.n.munoz@intel.com>

### CODE REVIEW

**Comment by markdryan** [comment]
@obedmr It would be nice to see some Info logs in the various commands.  Right now we won't know if an

**Comment by obedmr** [comment]
@markdryan got it. /me improving the PR. thanks

File: ciao-controller/openstack_image.go [hunk 1]
```diff
@@ -65,11 +67,14 @@ func (is ImageService) CreateImage(req image.CreateImageRequest) (image.DefaultR
 		CreateTime: time.Now(),
 	}
 
+	glog.Infof("Creating Image: %v", id)
```
Comment (markdryan) [inline ciao-controller/openstack_image.go]: I'd prefer to see this line at the start of the function, even if we don't know what the ID is.  Having it down here means that it might not always get output.

File: ciao-controller/openstack_image.go [hunk 2]
```diff
@@ -45,11 +45,13 @@ func (is ImageService) CreateImage(req image.CreateImageRequest) (image.DefaultR
...
 		if _, err := uuid.Parse(id); err != nil {
+			glog.Errorf("Error on parsing UUID: %v", err)
 			return image.DefaultResponse{}, image.ErrBadUUID
 		}
 
 		img, err := is.ds.GetImage(id)
 		if err != nil {
+			glog.Errorf("Error on deconding image: %v", err)
 			return image.DefaultResponse{}, image.ErrDecodeImage
 		}
```
Comment (markdryan) [inline ciao-controller/openstack_image.go]: We're missing a log in the case that the image already exists.

File: ciao-controller/openstack_image.go (hunk 1 above)
Comment (obedmr) [inline ciao-controller/openstack_image.go]: @markdryan done

File: ciao-controller/openstack_image.go (hunk 2 above)
Comment (obedmr) [inline ciao-controller/openstack_image.go]: @markdryan done, thanks

**Comment by obedmr** [comment]
@markdryan @rbradford, comments applied.
